### ISSUE TITLE
oAuth2 results in nullpointer exception

### ISSUE THREAD

**Issue by paul999** [wuman/android-oauth-client#40]
Hi,

With the current version (0.4.5), I get a nullpointer:
05-02 15:31:11.084  19604-19604/com.shoutbox_app.shoutboxapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.shoutbox_app.shoutboxapp, PID: 19604
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.api.client.http.HttpRequestInitializer.initialize(com.google.api.client.http.HttpRequest)' on a null object reference
            at com.wuman.android.auth.AuthorizationFlow$1.initialize(AuthorizationFlow.java:229)
            at com.wuman.android.auth.oauth2.explicit.LenientAuthorizationCodeTokenRequest$1.initialize(LenientAuthorizationCodeTokenRequest.java:142)
            at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:93)
            at com.google.api.client.http.HttpRequestFactory.buildPostRequest(HttpRequestFactory.java:133)
            at com.wuman.android.auth.oauth2.explicit.LenientAuthorizationCodeTokenRequest.executeLeniently(LenientAuthorizationCodeTokenRequest.java:158)
            at com.wuman.android.auth.oauth2.explicit.LenientAuthorizationCodeTokenRequest.execute(LenientAuthorizationCodeTokenRequest.java:104)
            at com.wuman.android.auth.OAuthManager$3.doWork(OAuthManager.java:206)
            at com.wuman.android.auth.OAuthManager$BaseFutureTask.startTask(OAuthManager.java:420)
            at com.wuman.android.auth.OAuthManager$Future2Task.start(OAuthManager.java:443)
            at com.wuman.android.auth.OAuthManager$5.run(OAuthManager.java:399)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

The cause seems to be coming from this commit: https://github.com/wuman/android-oauth-client/commit/13bb7654459a3538173d1b9da041564694462e93 I downgraded to 0.4.3, and afterwards it doesn't crash anymore.

**Comment by axd1967** [comment]
same here.
