### ISSUE TITLE
Broken: Samples/Simple OAuth 2.0 Explicit (foursquare)

### ISSUE THREAD

**Issue by loisaidasam** [wuman/android-oauth-client#48]
I'm basing an app I'm writing off of the Foursquare example, and yet when I run the samples app and attempt to click on the Explicit (foursquare) choice, I get the following:

    07-20 11:34:57.749    4619-4619/com.wuman.oauth.samples E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: com.wuman.oauth.samples, PID: 4619
        java.lang.IllegalArgumentException: Object returned from onCreateLoader must not be a non-static inner member class: GetTokenLoader{13750ad7 id=0}
                at android.support.v4.app.LoaderManagerImpl$LoaderInfo.start(LoaderManager.java:257)
                at android.support.v4.app.LoaderManagerImpl.installLoader(LoaderManager.java:513)
                at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:500)
                at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:553)
                at com.wuman.oauth.samples.foursquare.SimpleOAuth2ExplicitActivity$OAuthFragment$1.onClick(SimpleOAuth2ExplicitActivity.java:124)
                at android.view.View.performClick(View.java:4780)
                at android.view.View$PerformClick.run(View.java:19866)
                at android.os.Handler.handleCallback(Handler.java:739)
                at android.os.Handler.dispatchMessage(Handler.java:95)
                at android.os.Looper.loop(Looper.java:135)
                at android.app.ActivityThread.main(ActivityThread.java:5254)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Any insight?

**Comment by grptx** [comment]
any solution to this issue?
