### ISSUE TITLE
Dagger 2 annotation processor crash

### ISSUE THREAD

**Issue by 0ximDigital** [wuman/android-oauth-client#49]
Hi, project does not build after adding library via Gradle.

Stacktrace.. if it helps..
'''
An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.IllegalArgumentException: expected one element but was: <android.support.v4.app.FragmentActivity, android.support.v4.app.TaskStackBuilder.SupportParentable>
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:317)
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:329)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:302)
	at dagger.shaded.auto.common.MoreTypes.nonObjectSuperclass(MoreTypes.java:722)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.forInjectedType(MembersInjectionBinding.java:224)
	at dagger.internal.codegen.InjectBindingRegistry.getOrFindMembersInjectionBinding(InjectBindingRegistry.java:261)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:374)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:378)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:378)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:378)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.lookUpBindings(BindingGraph.java:366)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:461)
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:228)
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:151)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:76)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:228)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
etc..
'''

Note : Did not try to inject anything. i've just add gradle dependency and proguard rules.

Best regards

**Comment by quangson91** [comment]
@0ximDigital  You maybe check: https://stackoverflow.com/questions/35424372/dagger-2-inject-error-in-appcompatactivity/35424973#35424973

problem: maybe you added dagger in both library & app module.
Hope this help.
