### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by PhalugunaRao** [wuman/android-oauth-client#77]
java.lang.ClassCastException: com.google.api.client.auth.oauth2.AuthorizationCodeResponseUrl cannot be cast to com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl
        at com.google.api.client.auth.oauth2.AuthorizationCodeResponseUrl.set(AuthorizationCodeResponseUrl.java:222)
        at com.google.api.client.auth.oauth2.AuthorizationCodeResponseUrl.set(AuthorizationCodeResponseUrl.java:58)
        at com.google.api.client.http.UrlEncodedParser.parse(UrlEncodedParser.java:182)
        at com.google.api.client.http.UrlEncodedParser.parse(UrlEncodedParser.java:96)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:165)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:126)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:115)
        at com.google.api.client.auth.oauth2.AuthorizationCodeResponseUrl.<init>(AuthorizationCodeResponseUrl.java:99)
        at com.wuman.android.auth.OAuthDialogFragment$3.interceptUrlCompat(OAuthDialogFragment.java:361)
        at com.wuman.android.auth.OAuthDialogFragment$3.shouldOverrideUrlLoading(OAuthDialogFragment.java:316)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at yk.b(PG:89)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by PhalugunaRao** [comment]
How to solve this issue
